[build]
  command = "npm run build"  # The build command for your project
  publish = "build"          # The directory where your built files are located

[headers]
  # Define custom headers for your website
  "/*.html"
    Cache-Control = "public, max-age=0, must-revalidate"
  "/*.css"
    Cache-Control = "public, max-age=31536000, immutable"
  "/*.js"
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  # Define redirect rules
  from = "/old-page"
  to = "/new-page"
  status = 301

[[redirects]]
  # Another redirect rule example
  from = "/about-us"
  to = "/about"
  status = 301
